config/routes.rb
CSC517Project1BackChannelApp::Application.routes.draw do

  get "posts/reports"

  get "users/reports"

  get "users/showallusers"

  post "posts/votes"

  get "posts/upVote"

  get "posts/voteCount"

  get "users/search"

  resources :votes

  get "users/logout"

  post "posts/reply"

  get "posts/createreply"

  get "posts/votes"

  post "posts/search"

  get "users/index"

  post "posts/index"

  get "posts/new"

  resources :posts
  resources :users
  root :controller=>  "users", :action=> "authenticate"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :votes, :dependent => :destroy

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all
    @posts = Post.find(:all, :order=> "post_id")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id=session[:user_id]


    respond_to do |format|
      if @post.save
        parent_postid = @post.id
        @post.post_id=parent_postid
        @post.update_attribute("post_id", parent_postid)
        @post.update_attribute("user_id", session[:user_id])

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end

  def createreply
    @post = Post.find(params[:id])

  end

  def reply
    @post = Post.new
    @post.post_id = params[:parent_post_id]
    @post.post =  params[:post]
    @post.user_id = session[:user_id]

    respond_to do |format|
    if @post.save()
        format.html { redirect_to '/posts', notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
    end
    end
  end

  def upVote
    @post = Post.find(params[:id])
    @child_post = Post.find(:all, :conditions => "post_id = '#{params[:id]}'")

    if @post.id != @post.post_id
      @parent_post = Post.find(:first, :conditions => "id = '#{@post.post_id}'")
    end

    @vote = Vote.new
    @vote.post_id = params[:id]
    @vote.user_id = session[:user_id]
    @vote.save()

    @post.weight += 1

    @post.save()
    if !@parent_post.nil?
      @parent_post.weight += 1
      @parent_post.save()
    end

    redirect_to posts_path
  end

  def voteCount
    @post = Post.find(params[:id])
    @temp = Vote.find(:all, :conditions => "post_id = '#{@post.id}'")
    @count = @temp.size

  end


  def votes

    @vote = Vote.new
    #@post = Post.find(params[:id])
    @post.post_id = params[:parent_post_id]
    @post.user_id = session[:user_id]

    @vote.user_id = @post.user_id
    @vote.post_id = @post.post_id

    respond_to do |format|
    if @vote.save()
        format.html { redirect_to posts_path, notice: 'Voted successfully.' }
        format.json { render json: @vote, status: :created, location: @vote }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
    end
    end

    #@vote.new(:user_id => @post.user_id, :post_id => @post.post_id).save


    end

  def search
    @searchFor = params[:search]
    @searchType = params[:searchType]

    @searchFor = @searchFor.downcase

    @searchResult = ""
    if @searchType.to_s == "2"
      @keywords = "%".concat(@searchFor)
      @keywords = @keywords.split(" ").join("%")
      @searchResult = Post.find(:all, :conditions => "lower(post) like '#{@keywords}%' ")
    else
      @users = User.find(:all, :conditions => "lower(username) like '%#{@searchFor}%' or lower(fullname) like '%#{@searchFor}%'")

      if @users.size > 0
	      @userIdList = ""
	      @users.each do |users|
		@userIdList = @userIdList + users.id.to_s.concat(",")
	      end

	      @userIdList = @userIdList.chop


	      @searchResult = Post.find(:all, :conditions => "user_id in (#{@userIdList})")
	end
    end
    return @searchResult
  end

  def reports
    @posts = Post.all
    @posts = Post.find(:all, :order=> "post_id")

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_area :post %>
  </div>
  <!--<div class="field">
    <%= f.label :post_id %><br />
    <%= f.number_field :post_id %>
  </div>         -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/createreply.html.erb
<h3>Reply to</h3>

<p id="notice"><%= notice %></p>

<p>
  "<%= @post.post.to_s %>"
</p>

<%= form_tag posts_reply_path(:parent_post_id => @post.post_id) %>
<table>
  <tr>
    <td>
     Type your response here:
    </td>
    <td>
     <textarea id="post" name="post"></textarea>
    </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" align="center"><input type="submit" value=" Submit " /></td>
  </tr>

</table>
<br />

<%= link_to 'Back', posts_path %>

app/views/posts/edit.html.erb
<h3>Editing post</h3>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<table width="100%">
  <% if !session[:user_id].nil? %>
   <tr>
      <td>
        <%= link_to 'Create a post?', new_post_path %>
      </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
   <% end %>
  <% @posts = @posts.sort_by{|value| value.weight}
     @posts.reverse_each do |post| %>
    <tr>
      <td>
        <table bgcolor="#ECE5B6" border="1" bordercolor="white" width="100%">
          <% if post.id == post.post_id %>
          <tr>
              <td>

                <% @replies = Post.find(:all, :conditions => "id != #{post.id} and post_id = #{post.id}") %>
                   <table width="100%">
                     <tr>
                       <td colspan="2">
                           <%= post.post %>
                       </td>
                     </tr>
                     <% @replies.each do |reply| %>
                     <tr bgcolor="#ECD672">
                       <td bgcolor="#ECE5B6">&nbsp;&nbsp;</td>
                       <td>

                         &nbsp;&nbsp;&nbsp;<%= reply.post %>
                       <div align="right">
                         <table align="right" border="0" ><tr align="right">
                    <td colspan="2" valign="top" align="right">
                      <% user = User.find_by_sql("select username from users where id = '#{reply.user_id}'") %>
                      <b>By : <%= user[0].attributes['username'] %></b>
                    </td>
                  </tr> <tr><td width="80%">&nbsp;</td> <td class="round" align = "right" bgcolor="#7D1B7E"><font color="white">
                       <% @temp = Vote.find(:all, :conditions => "post_id = '#{reply.id}'")
                            @count = @temp.size %> <b><%= @count %> <br>votes</b>
                    </font></td></tr><tr><td colspan="2" align="right">
                        <% if reply.user_id == session[:user_id] && reply.id == reply.post_id%>
		                   &nbsp;|&nbsp; <%= link_to 'Edit', edit_post_path(reply)  %>
                        <% elsif reply.user_id == session[:user_id] && !(reply.id == reply.post_id) %>
                                <%= link_to 'Edit', edit_post_path(reply)  %>
	                    <% end %>
                        <% if session[:admin].to_s == "Admin" %>
		                    &nbsp;|&nbsp;<%= link_to 'Delete', reply, confirm: 'Are you sure?', method: :delete  %>
	                    <% end %>
	                    <% if !session[:user_id].nil? %>
                        <% @temp = Vote.find(:all, :conditions => "post_id = '#{reply.id}' and user_id = '#{session[:user_id]}'" ) %>
                      <% if !session[:user_id].nil? && !(reply.user_id == session[:user_id]) && !(@temp.size > 0) %>
		                    &nbsp;|&nbsp;<%= link_to 'Vote', posts_upVote_path(:id => reply.id) %>
                      <% end %>
			<% end %>
                      </tr></table>
                       </div>
                       </td>
                     </tr>
                     <% end %>
                   </table>

              </td>
              <td align="right" width="20%">
                <table>
                  <tr align="right">
                    <td colspan="4" valign="top" align="right">
                      <% user = User.find_by_sql("select username from users where id = '#{post.user_id}'") %>
                      <b>By : <%= user[0].attributes['username'] %></b>
                    </td>
                  </tr>
                  <tr>

                    <td colspan="4"><table width="25%" align="right"> <tr> <td class="round" align = "right" bgcolor="#7D1B7E"><font color="white">
                       <% @temp = Vote.find(:all, :conditions => "post_id = '#{post.id}'")
                            @count = @temp.size %> <b><%= @count %> <br>votes</b>
                    </font></td></tr></table></td>
                  </tr>
                  <tr align="right">
                    <td align="right">
                      <% if post.id == post.post_id && !session[:user_id].nil? %>
                        <%= link_to 'Reply', posts_createreply_path(:id => post.id) %>
                      <% end %>
                    </td>
                    <td align="right">
	                    <% if post.user_id == session[:user_id] && post.id == post.post_id%>
		                   &nbsp;|&nbsp; <%= link_to 'Edit', edit_post_path(post)  %>
                        <% elsif post.user_id == session[:user_id] && !(post.id == post.post_id) %>
                                <%= link_to 'Edit', edit_post_path(post)  %>
	                    <% end %>
                    </td>
                    <td align="right">
	                    <% if session[:admin].to_s == "Admin" %>
		                    &nbsp;|&nbsp;<%= link_to 'Delete', post, confirm: 'Are you sure?', method: :delete  %>
	                    <% end %>
                    </td>
                    <td align="right">
			<% if !session[:user_id].nil? %>
                      <% @temp = Vote.find(:all, :conditions => "post_id = '#{post.id}' and user_id = '#{session[:user_id]}'" ) %>
                      <% if !session[:user_id].nil? && !(post.user_id == session[:user_id]) && !(@temp.size > 0) %>
		                    &nbsp;|&nbsp;<%= link_to 'Vote', posts_upVote_path(:id => post.id) %>
                      <% end %>
                      <% end %>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <% end %>
        </table>
      </td>
    </tr>
  <% end %>

</table>

app/views/posts/new.html.erb
<h3>New post</h3>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/reply.html.erb
<h1>Posts#reply</h1>
<p>Find me in app/views/posts/reply.html.erb</p>

app/views/posts/reports.html.erb
<h3>Reports</h3>

<table bgcolor="#ECE5B6" border="1" bordercolor="white" width="100%">
    <font color="white"></font><tr bgcolor="#C8B560">
      <td align="center">
        <b>Post</b>
      </td>
      <td align="center">
        <b>Author</b>
      </td>
      <td align="center">
        <b>Number of votes for this post</b>
      </td>
    </tr></font>
    <% @posts.each do |post|
       if post.id == post.post_id
    %>
        <tr>
          <td>
            <%= post.post %><div align="right" ><%= link_to 'Go to post', post_path(post.id) %></div>
          </td>
          <td align="center">
            <% @user = User.find(:first, :conditions => "id = '#{post.user_id}'") %>
            <%= @user.username %>
          </td>
          <td align="center">
             <% @votes = Vote.find(:all, :conditions => "post_id = '#{post.id}'")
                
             %>
            <%= @votes.size %>
          </td>
        </tr>
      <% end %>
    <% end %>
</table>

app/views/posts/search.html.erb
<h4>Search Results for "<%= @searchFor %>"</h4>
<% if @searchResult.size > 0 %>

<%
   postFlag = Array.new
   maxpost = Post.find_by_sql("select max(id) as id from posts")
   i = 1
   puts "#{maxpost[0].attributes['id']}"
   while i <= maxpost[0].attributes['id'] do
    postFlag[i] = 0
    i = i + 1
   end
%>

<table bgcolor="#ECE5B6" border="1" bordercolor="white" width="100%">
    <% @searchResult.each do |post| %>

          <%

             if post.id != post.post_id
                @parentPost = Post.find(:first, :conditions => "id = #{post.post_id}")
             else
                @parentPost = post
             end
             if !@parentPost.nil?
             if postFlag[@parentPost.id] == 0
          %>
          <tr>
              <td>

                <% @replies = Post.find(:all, :conditions => "id != #{@parentPost.id} and post_id = #{@parentPost.id}") %>
                   <table width="100%">
                     <tr>
                       <td colspan="2">
                           <%= @parentPost.post %>
                       </td>
                     </tr>
                     <% @replies.each do |reply| %>
                     <tr bgcolor="#ECD672">
                       <td bgcolor="#ECE5B6">&nbsp;&nbsp;</td>
                       <td>
                         &nbsp;&nbsp;&nbsp;<%= reply.post %>
                       <div align="right"><table align="right" border="0" > <tr align="right">
                    <td colspan="2" valign="top" align="right">
                      <% user = User.find_by_sql("select username from users where id = '#{reply.user_id}'") %>
                      <b>By : <%= user[0].attributes['username'] %></b>
                    </td>
                  </tr><tr><td width="80%">&nbsp;</td> <td class="round" align = "right" bgcolor="#7D1B7E"><font color="white">
                       <% @temp = Vote.find(:all, :conditions => "post_id = '#{reply.id}'")
                            @count = @temp.size %> <b><%= @count %> <br>votes</b>
                    </font></td></tr><tr><td colspan="2" align="right">
                        <% if reply.user_id == session[:user_id] && reply.id == reply.post_id%>
		                   &nbsp;|&nbsp; <%= link_to 'Edit', edit_post_path(reply)  %>
                        <% elsif reply.user_id == session[:user_id] && !(reply.id == reply.post_id) %>
                                <%= link_to 'Edit', edit_post_path(reply)  %>
	                    <% end %>
                        <% if session[:admin].to_s == "Admin" %>
		                    &nbsp;|&nbsp;<%= link_to 'Delete', reply, confirm: 'Are you sure?', method: :delete  %>
	                    <% end %>
                         <% if !session[:user_id].nil? %>
                        <% @temp = Vote.find(:all, :conditions => "post_id = '#{reply.id}' and user_id = '#{session[:user_id]}'" ) %>
                      <% if !session[:user_id].nil? && !(reply.user_id == session[:user_id]) && !(@temp.size > 0) %>
		                    &nbsp;|&nbsp;<%= link_to 'Vote', posts_upVote_path(:id => reply.id) %>
                      <% end %>
                         <% end %>

                      </tr></table>
                       </div>
                       </td>
                     </tr>
                     <% end %>
                   </table>

              </td>
              <td align="right" width="20%">
                <table>
                  <tr align="right">
                    <td colspan="4" valign="top" align="right">
                      <% user = User.find_by_sql("select username from users where id = '#{@parentPost.user_id}'") %>
                      <b>By : <%= user[0].attributes['username'] %></b>
                    </td>
                  </tr>
                  <tr>

                    <td colspan="4"><table width="25%" align="right"> <tr> <td class="round" align = "right" bgcolor="#7D1B7E"><font color="white">
                       <% @temp = Vote.find(:all, :conditions => "post_id = '#{@parentPost.id}'")
                            @count = @temp.size %> <b><%= @count %> <br>votes</b>
                    </font></td></tr></table></td>
                  </tr>

                  <tr align="right">
                    <td align="right">
                      <% if @parentPost.id == @parentPost.post_id && !session[:user_id].nil? %>
                        <%= link_to 'Reply', posts_createreply_path(:id => @parentPost.id) %>
                      <% end %>
                    </td>
                    <td align="right">
	                    <% if @parentPost.user_id == session[:user_id] && @parentPost.id == @parentPost.post_id%>
		                   &nbsp;|&nbsp; <%= link_to 'Edit', edit_post_path(@parentPost)  %>
                        <% elsif @parentPost.user_id == session[:user_id] && !(@parentPost.id == @parentPost.post_id) %>
                                <%= link_to 'Edit', edit_post_path(@parentPost)  %>
	                    <% end %>
                    </td>
                    <td align="right">
	                    <% if session[:admin].to_s == "Admin" %>
		                    &nbsp;|&nbsp;<%= link_to 'Delete', @parentPost, confirm: 'Are you sure?', method: :delete  %>
	                    <% end %>
                    </td>
                    <td align="right">
		<% if !session[:user_id].nil? %>
                      <% @temp = Vote.find(:all, :conditions => "post_id = '#{@parentPost.id}' and user_id = '#{session[:user_id]}'" ) %>
                      <% if !session[:user_id].nil? && !(@parentPost.user_id == session[:user_id]) && !(@temp.size > 0) %>
		                    &nbsp;|&nbsp;<%= link_to 'Vote', posts_upVote_path(:id => @parentPost.id) %>
                      <% end %>
                      <% end %>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <% end

               if postFlag[@parentPost.id] == 0
                    postFlag[@parentPost.id] = 1
               end
              end
            end
          %>

</table>
<% else %>
<p> No results found </p>
<% end %>

app/views/posts/show.html.erb
<table width="100%">

    <tr>
      <td>
        <table bgcolor="#ECE5B6" border="1" bordercolor="white" width="100%">
          <% if @post.id == @post.post_id %>
          <tr>
              <td>

                <% @replies = Post.find(:all, :conditions => "id != #{@post.id} and post_id = #{@post.id}") %>
                   <table width="100%">
                     <tr>
                       <td colspan="2">
                           <%= @post.post %>
                       </td>
                     </tr>
                     <% @replies.each do |reply| %>
                     <tr bgcolor="#ECD672">
                       <td bgcolor="#ECE5B6">&nbsp;&nbsp;</td>
                       <td>
                         &nbsp;&nbsp;&nbsp;<%= reply.post %>
                       <div align="right">
                         <table align="right" border="0" ><tr align="right">
                    <td colspan="2" valign="top" align="right">
                      <% user = User.find_by_sql("select username from users where id = '#{reply.user_id}'") %>
                      <b>By : <%= user[0].attributes['username'] %></b>
                    </td>
                  </tr> <tr><td width="80%">&nbsp;</td> <td class="round" align = "right" bgcolor="#7D1B7E"><font color="white">
                       <% @temp = Vote.find(:all, :conditions => "post_id = '#{reply.id}'")
                            @count = @temp.size %> <b><%= @count %> <br>votes</b>
                    </font></td></tr><tr><td colspan="2" align="right">
                        <% if reply.user_id == session[:user_id] && reply.id == reply.post_id%>
		                   &nbsp;|&nbsp; <%= link_to 'Edit', edit_post_path(reply)  %>
                        <% elsif reply.user_id == session[:user_id] && !(reply.id == reply.post_id) %>
                                <%= link_to 'Edit', edit_post_path(reply)  %>
	                    <% end %>
                        <% if session[:admin].to_s == "Admin" %>
		                    &nbsp;|&nbsp;<%= link_to 'Delete', reply, confirm: 'Are you sure?', method: :delete  %>
	                    <% end %>
	              <% if !session[:user_id].nil? %>
                        <% @temp = Vote.find(:all, :conditions => "post_id = '#{reply.id}' and user_id = '#{session[:user_id]}'" ) %>
                      <% if !session[:user_id].nil? && !(reply.user_id == session[:user_id]) && !(@temp.size > 0) %>
		                    &nbsp;|&nbsp;<%= link_to 'Vote', posts_upVote_path(:id => reply.id) %>
                      <% end %>
			<% end %>
                      </tr></table>
                       </div>
                       </td>
                     </tr>
                     <% end %>
                   </table>

              </td>
              <td align="right" width="20%">
                <table>
                  <tr align="right">
                    <td colspan="2" valign="top" align="right">
                      <% user = User.find_by_sql("select username from users where id = '#{@post.user_id}'") %>
                      <b>By : <%= user[0].attributes['username'] %></b>
                    </td>
                  </tr>
                  <tr>

                    <td colspan="4"><table width="25%" align="right"> <tr> <td class="round" align = "right" bgcolor="#7D1B7E"><font color="white">
                       <% @temp = Vote.find(:all, :conditions => "post_id = '#{@post.id}'")
                            @count = @temp.size %> <b><%= @count %> <br>votes</b>
                    </font></td></tr></table></td>
                  </tr>
                  <tr align="right">
                    <td align="right">
                      <% if @post.id == @post.post_id && !session[:user_id].nil? %>
                        <%= link_to 'Reply', posts_createreply_path(:id => @post.id) %>
                      <% end %>
                    </td>
                    <td align="right">
	                    <% if @post.user_id == session[:user_id] && @post.id == @post.post_id%>
		                   &nbsp;|&nbsp; <%= link_to 'Edit', edit_post_path(@post)  %>
                        <% elsif @post.user_id == session[:user_id] && !(@post.id == @post.post_id) %>
                                <%= link_to 'Edit', edit_post_path(@post)  %>
	                    <% end %>
                    </td>
                    <td align="right">
	                    <% if session[:admin].to_s == "Admin" %>
		                    &nbsp;|&nbsp;<%= link_to 'Delete', @post, confirm: 'Are you sure?', method: :delete  %>
	                    <% end %>
                    </td>
                    <td align="right">
		<% if !session[:user_id].nil? %>
                      <% @temp = Vote.find(:all, :conditions => "post_id = '#{@post.id}' and user_id = '#{session[:user_id]}'" ) %>
                      <% if !session[:user_id].nil? && !(@post.user_id == session[:user_id]) && !(@temp.size > 0) %>
		                    &nbsp;|&nbsp;<%= link_to 'Vote', posts_upVote_path(:id => @post.id) %>
                      <% end %>
                     <% end %>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <% end %>
        </table>
      </td>
    </tr>


</table>

<%= link_to 'Back', :back %>

app/views/posts/upVote.html.erb
<h1>Posts#countvotes</h1>
<p>Find me in app/views/posts/countvotes.html.erb</p>

app/views/posts/votes.html.erb
<h1>Posts#votes</h1>
<p>Find me in app/views/posts/votes.html.erb</p>